{{- $name := "test-api" }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
spec:
  type: NodePort
  selector:
    app: {{ $name }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30000
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
spec:
  selector:
    matchLabels:
      app: {{ $name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers:
      - name: {{ $name }}
        image: {{ .Values.image }}
        ports:
          - containerPort: 3000
